export const ActionTypes = {
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  SET_PRODUCTS: "SET_PRODUCTS",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  FETCH_SINGLE_PRODUCT: "FETCH_SINGLE_PRODUCT",
  SELECT_PRODUCT: "SELECT_PRODUCT",
  ADD_PRODUCT: "ADD_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
  SET_EDIT: "SET_EDIT",
  SET_ADD: "SET_ADD",
};
